services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash scripts/startup.sh

  db:
    image: "postgres:17.2-alpine"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file:
      - .env
    ports:
      - "54323:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
